package ErpinventoryWs.unread;  
  
import java.io.*; 
import java.util.*; 
 
import javax.xml.bind.*; 
import javax.xml.datatype.*; 
 
 
// import java content classes generated by binding compiler 
import ErpinventoryWs.jaxb.*; 
 
public class UnmarshalRead { 
     
    // This sample application demonstrates how to unmarshal an instance 
    // document into a Java content tree and access data contained within it. 
     
    public static void main( String[] args ) { 
     
        try { 
            // create a JAXBContext capable of handling classes generated into 
            // the ErpinventoryWs.jaxb package 
            JAXBContext jc = JAXBContext.newInstance( "ErpinventoryWs.jaxb" ); 
             
            // create an Unmarshaller 
            Unmarshaller u = jc.createUnmarshaller(); 
             
            // unmarshal a (ErpinventoryWs) instance document into a tree of Java content 
            // objects composed of classes from package. 
            JAXBElement<?> wsElement = (JAXBElement<?>)u.unmarshal( new FileInputStream( "ErpinventoryWs.xml" ) ); 
 
		System.out.println("JAXBElement Name / Declared Type : "+ wsElement.getName() +" / "+ wsElement.getDeclaredType() );  
 
		ErpinventoryWs wsVar = (ErpinventoryWs) wsElement.getValue(); 
 
 
		ErpinventoryForm wsForm1 = (ErpinventoryForm) wsVar.getErpinventoryForm(); 
		Erpinventory tbl1 = wsForm1.getErpinventory(); 
		ErpinventoryRecords tblrecs1 = tbl1.getErpinventoryRecords(); 
		List<ErpinventoryRecords.ErpinventoryRec> tblreclist1 = tblrecs1.getErpinventoryRec(); 
		ListIterator iter1 = tblreclist1.listIterator(); 
		System.out.println("ErpinventoryForm : Erpinventory : Records : "); 
		while( iter1.hasNext()) { 
			ErpinventoryRecords.ErpinventoryRec tblrec1 = (ErpinventoryRecords.ErpinventoryRec) iter1.next(); 
			ErpinventoryFlds tblflds1 = (ErpinventoryFlds) tblrec1.getErpinventoryFlds(); 
 
		//Invid : Java Data Type [long], XML Schema Type [integer]  
		//tblflds1.getInvid();  
		//tblflds1.setInvid(); //1234 
		System.out.println("	Invid : " + tblflds1.getInvid() ); 
		//Productid : Java Data Type [long], XML Schema Type [integer]  
		//tblflds1.getProductid();  
		//tblflds1.setProductid(); //1234 
		System.out.println("	Productid : " + tblflds1.getProductid() ); 
		//Invdate : Java Data Type [Calendar], XML Schema Type [date]  
		//tblflds1.getInvdate();  
		//tblflds1.setInvdate(); //2006-06-01-05:30 
		System.out.println("	Invdate : " + tblflds1.getInvdate() ); 
		//Invqty : Java Data Type [long], XML Schema Type [integer]  
		//tblflds1.getInvqty();  
		//tblflds1.setInvqty(); //1234 
		System.out.println("	Invqty : " + tblflds1.getInvqty() ); 
		//Invminqty : Java Data Type [long], XML Schema Type [integer]  
		//tblflds1.getInvminqty();  
		//tblflds1.setInvminqty(); //1234 
		System.out.println("	Invminqty : " + tblflds1.getInvminqty() ); 
		//Invcost : Java Data Type [float], XML Schema Type [float]  
		//tblflds1.getInvcost();  
		//tblflds1.setInvcost(); //1234.56 
		System.out.println("	Invcost : " + tblflds1.getInvcost() ); 
		//Invlocation : Java Data Type [String], XML Schema Type [string]  
		//tblflds1.getInvlocation();  
		//tblflds1.setInvlocation(); //ABCD_string 
		System.out.println("	Invlocation : " + tblflds1.getInvlocation() ); 
		RecInfo ri1 = tblrec1.getRecInfo(); 
		System.out.println("  RecInfo : "+ri1.getSrlNo()+" , "+ri1.getRecNo()); 
 
		} //while 
 
		WpInfo wi1 = wsForm1.getWpInfo(); 
		System.out.println("  WpInfo : "+wi1.getWpStatus()+" , "+wi1.getWpRecords()); 
		System.out.println("END : ErpinventoryForm : Erpinventory : Records : "); 
 
 
 
        Marshaller m1 = jc.createMarshaller();  
        m1.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, true); 
        m1.marshal(wsElement, System.out); 
          
        } catch( JAXBException je ) { 
            je.printStackTrace(); 
        } catch( IOException ioe ) { 
            ioe.printStackTrace(); 
        } 
    } 
} 
