package ErpproductWs.unread;  
  
import java.io.*; 
import java.util.*; 
 
import javax.xml.bind.*; 
import javax.xml.datatype.*; 
 
 
// import java content classes generated by binding compiler 
import ErpproductWs.jaxb.*; 
 
public class UnmarshalRead { 
     
    // This sample application demonstrates how to unmarshal an instance 
    // document into a Java content tree and access data contained within it. 
     
    public static void main( String[] args ) { 
     
        try { 
            // create a JAXBContext capable of handling classes generated into 
            // the ErpproductWs.jaxb package 
            JAXBContext jc = JAXBContext.newInstance( "ErpproductWs.jaxb" ); 
             
            // create an Unmarshaller 
            Unmarshaller u = jc.createUnmarshaller(); 
             
            // unmarshal a (ErpproductWs) instance document into a tree of Java content 
            // objects composed of classes from package. 
            JAXBElement<?> wsElement = (JAXBElement<?>)u.unmarshal( new FileInputStream( "ErpproductWs.xml" ) ); 
 
		System.out.println("JAXBElement Name / Declared Type : "+ wsElement.getName() +" / "+ wsElement.getDeclaredType() );  
 
		ErpproductWs wsVar = (ErpproductWs) wsElement.getValue(); 
 
 
		ErpproductForm wsForm1 = (ErpproductForm) wsVar.getErpproductForm(); 
		Erpproduct tbl1 = wsForm1.getErpproduct(); 
		ErpproductRecords tblrecs1 = tbl1.getErpproductRecords(); 
		List<ErpproductRecords.ErpproductRec> tblreclist1 = tblrecs1.getErpproductRec(); 
		ListIterator iter1 = tblreclist1.listIterator(); 
		System.out.println("ErpproductForm : Erpproduct : Records : "); 
		while( iter1.hasNext()) { 
			ErpproductRecords.ErpproductRec tblrec1 = (ErpproductRecords.ErpproductRec) iter1.next(); 
			ErpproductFlds tblflds1 = (ErpproductFlds) tblrec1.getErpproductFlds(); 
 
		//Productid : Java Data Type [long], XML Schema Type [integer]  
		//tblflds1.getProductid();  
		//tblflds1.setProductid(); //1234 
		System.out.println("	Productid : " + tblflds1.getProductid() ); 
		//Productname : Java Data Type [String], XML Schema Type [string]  
		//tblflds1.getProductname();  
		//tblflds1.setProductname(); //ABCD_string 
		System.out.println("	Productname : " + tblflds1.getProductname() ); 
		//Productcategory : Java Data Type [String], XML Schema Type [string]  
		//tblflds1.getProductcategory();  
		//tblflds1.setProductcategory(); //ABCD_string 
		System.out.println("	Productcategory : " + tblflds1.getProductcategory() ); 
		//Primarysupplier : Java Data Type [String], XML Schema Type [string]  
		//tblflds1.getPrimarysupplier();  
		//tblflds1.setPrimarysupplier(); //ABCD_string 
		System.out.println("	Primarysupplier : " + tblflds1.getPrimarysupplier() ); 
		//Productdesc : Java Data Type [String], XML Schema Type [string]  
		//tblflds1.getProductdesc();  
		//tblflds1.setProductdesc(); //ABCD_string 
		System.out.println("	Productdesc : " + tblflds1.getProductdesc() ); 
		//Productpicture : Java Data Type [byte[]], XML Schema Type [base64Binary]  
		//tblflds1.getProductpicture();  
		//tblflds1.setProductpicture(); //base64Binary_DATA 
		System.out.println("	Productpicture : " + tblflds1.getProductpicture() ); 
		RecInfo ri1 = tblrec1.getRecInfo(); 
		System.out.println("  RecInfo : "+ri1.getSrlNo()+" , "+ri1.getRecNo()); 
 
		} //while 
 
		WpInfo wi1 = wsForm1.getWpInfo(); 
		System.out.println("  WpInfo : "+wi1.getWpStatus()+" , "+wi1.getWpRecords()); 
		System.out.println("END : ErpproductForm : Erpproduct : Records : "); 
 
 
 
        Marshaller m1 = jc.createMarshaller();  
        m1.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, true); 
        m1.marshal(wsElement, System.out); 
          
        } catch( JAXBException je ) { 
            je.printStackTrace(); 
        } catch( IOException ioe ) { 
            ioe.printStackTrace(); 
        } 
    } 
} 
