package ErpsalesinquiryWs.unread;  
  
import java.io.*; 
import java.util.*; 
 
import javax.xml.bind.*; 
import javax.xml.datatype.*; 
 
 
// import java content classes generated by binding compiler 
import ErpsalesinquiryWs.jaxb.*; 
 
public class UnmarshalRead { 
     
    // This sample application demonstrates how to unmarshal an instance 
    // document into a Java content tree and access data contained within it. 
     
    public static void main( String[] args ) { 
     
        try { 
            // create a JAXBContext capable of handling classes generated into 
            // the ErpsalesinquiryWs.jaxb package 
            JAXBContext jc = JAXBContext.newInstance( "ErpsalesinquiryWs.jaxb" ); 
             
            // create an Unmarshaller 
            Unmarshaller u = jc.createUnmarshaller(); 
             
            // unmarshal a (ErpsalesinquiryWs) instance document into a tree of Java content 
            // objects composed of classes from package. 
            JAXBElement<?> wsElement = (JAXBElement<?>)u.unmarshal( new FileInputStream( "ErpsalesinquiryWs.xml" ) ); 
 
		System.out.println("JAXBElement Name / Declared Type : "+ wsElement.getName() +" / "+ wsElement.getDeclaredType() );  
 
		ErpsalesinquiryWs wsVar = (ErpsalesinquiryWs) wsElement.getValue(); 
 
 
		ErpsalesinquiryForm wsForm1 = (ErpsalesinquiryForm) wsVar.getErpsalesinquiryForm(); 
		Erpsalesinquiry tbl1 = wsForm1.getErpsalesinquiry(); 
		ErpsalesinquiryRecords tblrecs1 = tbl1.getErpsalesinquiryRecords(); 
		List<ErpsalesinquiryRecords.ErpsalesinquiryRec> tblreclist1 = tblrecs1.getErpsalesinquiryRec(); 
		ListIterator iter1 = tblreclist1.listIterator(); 
		System.out.println("ErpsalesinquiryForm : Erpsalesinquiry : Records : "); 
		while( iter1.hasNext()) { 
			ErpsalesinquiryRecords.ErpsalesinquiryRec tblrec1 = (ErpsalesinquiryRecords.ErpsalesinquiryRec) iter1.next(); 
			ErpsalesinquiryFlds tblflds1 = (ErpsalesinquiryFlds) tblrec1.getErpsalesinquiryFlds(); 
 
		//DateOfInquiry : Java Data Type [Calendar], XML Schema Type [date]  
		//tblflds1.getDateOfInquiry();  
		//tblflds1.setDateOfInquiry(); //2006-06-01-05:30 
		System.out.println("	DateOfInquiry : " + tblflds1.getDateOfInquiry() ); 
		//RequestedQty : Java Data Type [long], XML Schema Type [integer]  
		//tblflds1.getRequestedQty();  
		//tblflds1.setRequestedQty(); //1234 
		System.out.println("	RequestedQty : " + tblflds1.getRequestedQty() ); 
		//ReqQuoteAmt : Java Data Type [float], XML Schema Type [float]  
		//tblflds1.getReqQuoteAmt();  
		//tblflds1.setReqQuoteAmt(); //1234.56 
		System.out.println("	ReqQuoteAmt : " + tblflds1.getReqQuoteAmt() ); 
		//MeetingPrefTime : Java Data Type [Calendar], XML Schema Type [time]  
		//tblflds1.getMeetingPrefTime();  
		//tblflds1.setMeetingPrefTime(); //14:10:00-05:30 
		System.out.println("	MeetingPrefTime : " + tblflds1.getMeetingPrefTime() ); 
		//Created : Java Data Type [Calendar], XML Schema Type [dateTime]  
		//tblflds1.getCreated();  
		//tblflds1.setCreated(); //2006-06-01T14:10:00-05:30 
		System.out.println("	Created : " + tblflds1.getCreated() ); 
		//Updated : Java Data Type [Calendar], XML Schema Type [dateTime]  
		//tblflds1.getUpdated();  
		//tblflds1.setUpdated(); //2006-06-01T14:10:00-05:30 
		System.out.println("	Updated : " + tblflds1.getUpdated() ); 
		RecInfo ri1 = tblrec1.getRecInfo(); 
		System.out.println("  RecInfo : "+ri1.getSrlNo()+" , "+ri1.getRecNo()); 
 
		} //while 
 
		WpInfo wi1 = wsForm1.getWpInfo(); 
		System.out.println("  WpInfo : "+wi1.getWpStatus()+" , "+wi1.getWpRecords()); 
		System.out.println("END : ErpsalesinquiryForm : Erpsalesinquiry : Records : "); 
 
 
 
        Marshaller m1 = jc.createMarshaller();  
        m1.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, true); 
        m1.marshal(wsElement, System.out); 
          
        } catch( JAXBException je ) { 
            je.printStackTrace(); 
        } catch( IOException ioe ) { 
            ioe.printStackTrace(); 
        } 
    } 
} 
