package ErpinventorysumvwWs.unread;  
  
import java.io.*; 
import java.util.*; 
 
import javax.xml.bind.*; 
import javax.xml.datatype.*; 
 
 
// import java content classes generated by binding compiler 
import ErpinventorysumvwWs.jaxb.*; 
 
public class UnmarshalRead { 
     
    // This sample application demonstrates how to unmarshal an instance 
    // document into a Java content tree and access data contained within it. 
     
    public static void main( String[] args ) { 
     
        try { 
            // create a JAXBContext capable of handling classes generated into 
            // the ErpinventorysumvwWs.jaxb package 
            JAXBContext jc = JAXBContext.newInstance( "ErpinventorysumvwWs.jaxb" ); 
             
            // create an Unmarshaller 
            Unmarshaller u = jc.createUnmarshaller(); 
             
            // unmarshal a (ErpinventorysumvwWs) instance document into a tree of Java content 
            // objects composed of classes from package. 
            JAXBElement<?> wsElement = (JAXBElement<?>)u.unmarshal( new FileInputStream( "ErpinventorysumvwWs.xml" ) ); 
 
		System.out.println("JAXBElement Name / Declared Type : "+ wsElement.getName() +" / "+ wsElement.getDeclaredType() );  
 
		ErpinventorysumvwWs wsVar = (ErpinventorysumvwWs) wsElement.getValue(); 
 
 
		ErpinventorysumvwForm wsForm1 = (ErpinventorysumvwForm) wsVar.getErpinventorysumvwForm(); 
		Erpinventorysumvw tbl1 = wsForm1.getErpinventorysumvw(); 
		ErpinventorysumvwRecords tblrecs1 = tbl1.getErpinventorysumvwRecords(); 
		List<ErpinventorysumvwRecords.ErpinventorysumvwRec> tblreclist1 = tblrecs1.getErpinventorysumvwRec(); 
		ListIterator iter1 = tblreclist1.listIterator(); 
		System.out.println("ErpinventorysumvwForm : Erpinventorysumvw : Records : "); 
		while( iter1.hasNext()) { 
			ErpinventorysumvwRecords.ErpinventorysumvwRec tblrec1 = (ErpinventorysumvwRecords.ErpinventorysumvwRec) iter1.next(); 
			ErpinventorysumvwFlds tblflds1 = (ErpinventorysumvwFlds) tblrec1.getErpinventorysumvwFlds(); 
 
		//Year : Java Data Type [long], XML Schema Type [integer]  
		//tblflds1.getYear();  
		//tblflds1.setYear(); //1234 
		System.out.println("	Year : " + tblflds1.getYear() ); 
		//Month : Java Data Type [long], XML Schema Type [integer]  
		//tblflds1.getMonth();  
		//tblflds1.setMonth(); //1234 
		System.out.println("	Month : " + tblflds1.getMonth() ); 
		//Totalqty : Java Data Type [float], XML Schema Type [float]  
		//tblflds1.getTotalqty();  
		//tblflds1.setTotalqty(); //1234.56 
		System.out.println("	Totalqty : " + tblflds1.getTotalqty() ); 
		RecInfo ri1 = tblrec1.getRecInfo(); 
		System.out.println("  RecInfo : "+ri1.getSrlNo()+" , "+ri1.getRecNo()); 
 
		} //while 
 
		WpInfo wi1 = wsForm1.getWpInfo(); 
		System.out.println("  WpInfo : "+wi1.getWpStatus()+" , "+wi1.getWpRecords()); 
		System.out.println("END : ErpinventorysumvwForm : Erpinventorysumvw : Records : "); 
 
 
 
        Marshaller m1 = jc.createMarshaller();  
        m1.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, true); 
        m1.marshal(wsElement, System.out); 
          
        } catch( JAXBException je ) { 
            je.printStackTrace(); 
        } catch( IOException ioe ) { 
            ioe.printStackTrace(); 
        } 
    } 
} 
